try:
    print('Running the try...')
    print('5'+5)
    
except Exception as e:
    print(str(e))
    
